# Generated by Django 4.0.5 on 2022-06-20 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
