# Generated by Django 4.0.5 on 2022-06-20 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_bid_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedlisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchedlisting',
            name='watched_listing',
            field=models.ManyToManyField(blank=True, related_name='watched_listings', to='auctions.listing'),
        ),
    ]
