# Generated by Django 4.0.5 on 2022-06-20 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_watchedlisting_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedlisting',
            name='watched_listing',
        ),
        migrations.AddField(
            model_name='watchedlisting',
            name='watched_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_listings', to='auctions.listing'),
        ),
    ]
