# Generated by Django 4.0.5 on 2022-06-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_watchedlisting_watched_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='Default text for a comment.'),
            preserve_default=False,
        ),
    ]
